let books = [
  { id: "1", title: "Gitanjali", author_ids: ["1"], isFavorite: false, about: "Gitanjali is a collection of poems by the Bengali poet Rabindranath Tagore. Tagore received the Nobel Prize for Literature in 1913 for its English translation, Song Offerings.", image_url: "https://example.com/gitanjali.jpg" },
  { id: "2", title: "The God of Small Things", author_ids: ["2"], isFavorite: false, about: "The God of Small Things is a novel by Arundhati Roy. It explores childhood experiences, casteism, and the social issues prevalent in India.", image_url: "https://example.com/the_god_of_small_things.jpg" },
  { id: "3", title: "Five Point Someone", author_ids: ["3"], isFavorite: false, about: "Five Point Someone: What not to do at IIT is a 2004 novel by Chetan Bhagat. It focuses on the struggles of three friends in IIT.", image_url: "https://example.com/five_point_someone.jpg" },
  { id: "4", title: "The Immortals of Meluha", author_ids: ["4"], isFavorite: false, about: "The Immortals of Meluha is a fantasy novel by Amish Tripathi and the first book in the Shiva Trilogy.", image_url: "https://example.com/the_immortals_of_meluha.jpg" },
  { id: "5", title: "Midnight's Children", author_ids: ["5", "13"], isFavorite: false, about: "Midnight's Children by Salman Rushdie deals with India's transition from British colonialism to independence.", image_url: "https://example.com/midnights_children.jpg" },
  { id: "6", title: "The White Tiger", author_ids: ["6"], isFavorite: false, about: "The White Tiger by Aravind Adiga is a darkly humorous novel exploring class struggle in India.", image_url: "https://example.com/the_white_tiger.jpg" },
  { id: "7", title: "Train to Pakistan", author_ids: ["7"], isFavorite: false, about: "Train to Pakistan is a historical novel by Khushwant Singh focusing on the Partition of India.", image_url: "https://example.com/train_to_pakistan.jpg" },
  { id: "8", title: "The Inheritance of Loss", author_ids: ["8", "9"], isFavorite: false, about: "The Inheritance of Loss by Kiran Desai deals with globalization and multiculturalism, set in postcolonial India.", image_url: "https://example.com/the_inheritance_of_loss.jpg" },
  { id: "9", title: "A Suitable Boy", author_ids: ["9"], isFavorite: false, about: "A Suitable Boy by Vikram Seth is one of the longest novels ever published in a single volume in the English language.", image_url: "https://example.com/a_suitable_boy.jpg" },
  { id: "10", title: "Shantaram", author_ids: ["10"], isFavorite: false, about: "Shantaram by Gregory David Roberts narrates the author's adventures in the underworld of Bombay.", image_url: "https://example.com/shantaram.jpg" },
  { id: "11", title: "The Discovery of India", author_ids: ["11"], isFavorite: false, about: "The Discovery of India by Jawaharlal Nehru is a tribute to India's rich cultural heritage, written during his imprisonment by the British.", image_url: "https://example.com/the_discovery_of_india.jpg" },
  { id: "12", title: "Sea of Poppies", author_ids: ["12"], isFavorite: false, about: "Sea of Poppies by Amitav Ghosh traces the stories of diverse characters aboard a ship sailing from Calcutta to Mauritius.", image_url: "https://example.com/sea_of_poppies.jpg" },
  { id: "13", title: "The Palace of Illusions", author_ids: ["13"], isFavorite: false, about: "The Palace of Illusions by Chitra Banerjee Divakaruni retells the Mahabharata from Draupadi's perspective.", image_url: "https://example.com/the_palace_of_illusions.jpg" },
  { id: "14", title: "The Broken Republic", author_ids: ["2", "14"], isFavorite: false, about: "The Broken Republic is a collection of essays by Arundhati Roy focusing on India's Maoist insurgency.", image_url: "https://example.com/the_broken_republic.jpg" },
  { id: "15", title: "2 States", author_ids: ["3"], isFavorite: false, about: "2 States by Chetan Bhagat is a semi-autobiographical novel about a couple from different Indian states.", image_url: "https://example.com/2_states.jpg" },
  { id: "16", title: "The Oath of the Vayuputras", author_ids: ["4", "12"], isFavorite: false, about: "The Oath of the Vayuputras is the third book in Amish Tripathi's Shiva Trilogy.", image_url: "https://example.com/the_oath_of_the_vayuputras.jpg" },
  { id: "17", title: "The Satanic Verses", author_ids: ["5"], isFavorite: false, about: "The Satanic Verses by Salman Rushdie is a controversial novel that mixes elements of magical realism and religion.", image_url: "https://example.com/the_satanic_verses.jpg" },
  { id: "18", title: "The Elephant Paradigm", author_ids: ["6"], isFavorite: false, about: "The Elephant Paradigm is a collection of essays by Aravind Adiga, exploring India's economic and social changes.", image_url: "https://example.com/the_elephant_paradigm.jpg" },
  { id: "19", title: "Delhi: A Novel", author_ids: ["7"], isFavorite: false, about: "Delhi: A Novel by Khushwant Singh is a historical and erotic novel about the city of Delhi.", image_url: "https://example.com/delhi_a_novel.jpg" },
  { id: "20", title: "An Equal Music", author_ids: ["9", "8"], isFavorite: false, about: "An Equal Music by Vikram Seth is a novel about love, music, and passion.", image_url: "https://example.com/an_equal_music.jpg" }
];

let authors = [
  { id: "1", name: "Rabindranath Tagore", book_ids: ["1"], image_url: "https://example.com/rabindranath_tagore.jpg", about: "Rabindranath Tagore was a Bengali polymath, poet, musician, and artist.", isFavorite: false },
  { id: "2", name: "Arundhati Roy", book_ids: ["2", "14"], image_url: "https://example.com/arundhati_roy.jpg", about: "Arundhati Roy is an Indian author and political activist known for her novel 'The God of Small Things'.", isFavorite: false },
  { id: "3", name: "Chetan Bhagat", book_ids: ["3", "15"], image_url: "https://example.com/chetan_bhagat.jpg", about: "Chetan Bhagat is an Indian author and motivational speaker known for his novels on contemporary Indian youth.", isFavorite: false },
  { id: "4", name: "Amish Tripathi", book_ids: ["4", "16"], image_url: "https://example.com/amish_tripathi.jpg", about: "Amish Tripathi is an Indian author known for his mythological fiction.", isFavorite: false },
  { id: "5", name: "Salman Rushdie", book_ids: ["5", "17"], image_url: "https://example.com/salman_rushdie.jpg", about: "Salman Rushdie is a British-Indian author and essayist known for his magical realism.", isFavorite: false },
  { id: "6", name: "Aravind Adiga", book_ids: ["6", "18"], image_url: "https://example.com/aravind_adiga.jpg", about: "Aravind Adiga is an Indian author and journalist, best known for 'The White Tiger'.", isFavorite: false },
  { id: "7", name: "Khushwant Singh", book_ids: ["7", "19"], image_url: "https://example.com/khushwant_singh.jpg", about: "Khushwant Singh was an Indian author, lawyer, diplomat, journalist, and politician.", isFavorite: false },
  { id: "8", name: "Kiran Desai", book_ids: ["8", "20"], image_url: "https://example.com/kiran_desai.jpg", about: "Kiran Desai is an Indian author known for her Booker Prize-winning novel 'The Inheritance of Loss'.", isFavorite: false },
  { id: "9", name: "Vikram Seth", book_ids: ["9", "20"], image_url: "https://example.com/vikram_seth.jpg", about: "Vikram Seth is an Indian poet, novelist, and children's writer known for 'A Suitable Boy'.", isFavorite: false },
  { id: "10", name: "Gregory David Roberts", book_ids: ["10"], image_url: "https://example.com/gregory_david_roberts.jpg", about: "Gregory David Roberts is an Australian author known for his novel 'Shantaram'.", isFavorite: false },
  { id: "11", name: "Jawaharlal Nehru", book_ids: ["11"], image_url: "https://example.com/jawaharlal_nehru.jpg", about: "Jawaharlal Nehru was the first Prime Minister of India and a prominent leader in the Indian independence movement.", isFavorite: false },
  { id: "12", name: "Amitav Ghosh", book_ids: ["12"], image_url: "https://example.com/amitav_ghosh.jpg", about: "Amitav Ghosh is an Indian author known for his historical fiction and novels exploring cultural histories.", isFavorite: false },
  { id: "13", name: "Chitra Banerjee Divakaruni", book_ids: ["13"], image_url: "https://example.com/chitra_banerjee_divakaruni.jpg", about: "Chitra Banerjee Divakaruni is an Indian-American author known for her novels on the Indian diaspora.", isFavorite: false }
];

let bookReviews = [
  { id: "1", book_id: "1", content: "A beautiful collection of poetry that speaks to the soul.", rating: 5 },
  { id: "2", book_id: "1", content: "Tagore's insights on life and nature are profound.", rating: 4 },
  { id: "3", book_id: "1", content: "Every poem feels like a gentle breeze, refreshing and thought-provoking.", rating: 5 },
  { id: "4", book_id: "2", content: "A haunting narrative that beautifully captures the complexities of love.", rating: 5 },
  { id: "5", book_id: "2", content: "The way Roy describes the characters' emotions is simply mesmerizing.", rating: 5 },
  { id: "6", book_id: "3", content: "An entertaining read that reflects on student life in India.", rating: 4 },
  { id: "7", book_id: "3", content: "Bhagat's relatable writing style makes it easy to connect with the characters.", rating: 4 },
  { id: "8", book_id: "4", content: "An epic story that brings mythology to life.", rating: 5 },
  { id: "9", book_id: "4", content: "A fascinating blend of fiction and ancient tales!", rating: 5 },
  { id: "10", book_id: "5", content: "A remarkable narrative that intertwines personal and historical events.", rating: 5 },
  { id: "11", book_id: "5", content: "Rushdie's ability to weave multiple narratives is unparalleled.", rating: 5 },
  { id: "12", book_id: "6", content: "A gripping tale of class struggles in modern India.", rating: 4 },
  { id: "13", book_id: "6", content: "Adiga sheds light on the stark contrasts within Indian society.", rating: 4 },
  { id: "14", book_id: "7", content: "A powerful account of the impact of partition.", rating: 5 },
  { id: "15", book_id: "7", content: "Singh's storytelling is poignant and heartfelt.", rating: 5 },
  { id: "16", book_id: "8", content: "Beautifully written and deeply moving.", rating: 4 },
  { id: "17", book_id: "8", content: "Desai's characters are intricately woven into a tapestry of loss and belonging.", rating: 4 },
  { id: "18", book_id: "9", content: "A masterful exploration of love and societal norms.", rating: 5 },
  { id: "19", book_id: "9", content: "Seth's narrative is both sweeping and intimate.", rating: 5 },
  { id: "20", book_id: "10", content: "A compelling story that captures the essence of Bombay's underworld.", rating: 5 },
  { id: "21", book_id: "10", content: "Roberts paints a vivid picture of life in the slums.", rating: 5 },
  { id: "22", book_id: "11", content: "An insightful look into India's cultural heritage.", rating: 5 },
  { id: "23", book_id: "11", content: "Nehru's observations are as relevant today as they were then.", rating: 5 },
  { id: "24", book_id: "12", content: "A rich tapestry of stories that reflects historical realities.", rating: 4 },
  { id: "25", book_id: "12", content: "Ghosh's narrative is both engaging and informative.", rating: 4 },
  { id: "26", book_id: "13", content: "An innovative retelling of a classic epic.", rating: 5 },
  { id: "27", book_id: "13", content: "Divakaruni's perspective adds depth to the Mahabharata.", rating: 5 }
];

let authorReviews = [
  { id: "1", author_id: "1", content: "Tagore's works are timeless and deeply philosophical.", rating: 5 },
  { id: "2", author_id: "1", content: "His poetry resonates across generations.", rating: 5 },
  { id: "3", author_id: "1", content: "Every line he wrote feels like it came straight from the heart.", rating: 5 },
  { id: "4", author_id: "2", content: "Roy's writing is powerful and thought-provoking.", rating: 5 },
  { id: "5", author_id: "2", content: "She masterfully captures the nuances of Indian society.", rating: 5 },
  { id: "6", author_id: "3", content: "Chetan Bhagat connects well with the youth of India.", rating: 4 },
  { id: "7", author_id: "3", content: "His stories reflect the challenges faced by modern Indian youth.", rating: 4 },
  { id: "8", author_id: "4", content: "Amish Tripathi brings mythology to a modern audience.", rating: 5 },
  { id: "9", author_id: "4", content: "His retellings make ancient tales feel contemporary.", rating: 5 },
  { id: "10", author_id: "5", content: "Rushdie's narratives are complex yet beautifully crafted.", rating: 5 },
  { id: "11", author_id: "5", content: "He challenges readers to think beyond the ordinary.", rating: 5 },
  { id: "12", author_id: "6", content: "Adiga's sharp observations on society are commendable.", rating: 4 },
  { id: "13", author_id: "6", content: "His writing style is both engaging and reflective.", rating: 4 },
  { id: "14", author_id: "7", content: "Khushwant Singh's humor and wit are unparalleled.", rating: 5 },
  { id: "15", author_id: "7", content: "His writing brings history to life in a unique way.", rating: 5 },
  { id: "16", author_id: "8", content: "Desai's prose is lyrical and evocative.", rating: 4 },
  { id: "17", author_id: "8", content: "She beautifully captures the immigrant experience.", rating: 4 },
  { id: "18", author_id: "9", content: "Seth's storytelling is engaging and rich.", rating: 5 },
  { id: "19", author_id: "9", content: "He weaves intricate narratives that captivate readers.", rating: 5 },
  { id: "20", author_id: "10", content: "Roberts' personal experiences lend authenticity to his writing.", rating: 5 },
  { id: "21", author_id: "10", content: "He creates vivid imagery of the places he describes.", rating: 5 },
  { id: "22", author_id: "11", content: "Nehru's insights into India are invaluable.", rating: 5 },
  { id: "23", author_id: "11", content: "His perspectives on democracy and freedom are enlightening.", rating: 5 },
  { id: "24", author_id: "12", content: "Ghosh's historical context adds depth to his stories.", rating: 4 },
  { id: "25", author_id: "12", content: "His characters are well-developed and relatable.", rating: 4 },
  { id: "26", author_id: "13", content: "Divakaruni's exploration of culture and identity is profound.", rating: 5 },
  { id: "27", author_id: "13", content: "Her narratives bring out the complexities of womanhood beautifully.", rating: 5 }
];


export default { books, authors, bookReviews, authorReviews }